Formatting and Code deduplication

diff --git a/gnome-debloater b/gnome-debloater
--- a/gnome-debloater
+++ b/gnome-debloater
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e
+
 help="Welcome to gnome-debloater, 
 this program is used to debloat the 
 gnome in different debian installs.
@@ -8,40 +10,54 @@ d(x) refers to different debian editions.
 
 EX: dt is debian testing.
 
-h < displays the help message
+h    < displays the help message
 doos < debloats debian stretch
-dos < debloat debian buster
-ds < debloats debian bullseye
-dt < debloats debian bookworm
-dus < debloats debian sid"
+dos  < debloats debian buster
+ds   < debloats debian bullseye
+dt   < debloats debian bookworm
+dus  < debloats debian sid"
 
 case $1 in
-        h | help)
-	        echo "$help"
-		;;
-		
-	doos | debian-oldoldstable)
-		sudo apt purge gimp inkscape brasero reportbug polari gnome-dictionary gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music simple-scan vinagre file-roller gnome-documents && sudo apt autoremove && sudo apt upgrade && sudo apt update
-		;;
-		
-	dos | debian-oldstable)
-		sudo apt purge gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music simple-scan vinagre file-roller gnome-documents && sudo apt autoremove && sudo apt upgrade && sudo apt update
-		;;
-				
-	ds | debian-stable)
-		sudo apt purge gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents && sudo apt autoremove && sudo apt upgrade && sudo apt update
-		;;
+	h | help ) echo "$help" ;;
 
-	dt | debian-testing)
-		sudo apt purge epiphany gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents seahorse && sudo apt autoremove && sudo apt install gnome-connections power-profiles-daemon && sudo apt upgrade && sudo apt update
-		;;
-       
-	dus | debian-unstable)
-		sudo apt purge epiphany gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents seahorse && sudo apt autoremove && sudo apt install gnome-connections power-profiles-daemon && sudo apt upgrade && sudo apt update
-		;;
-     
-	*)
-		echo "$help"
-		;;
+	doos )
+		apt-get-get purge gimp inkscape brasero reportbug polari \
+			gnome-dictionary gnome-games gnome-sound-recorder \
+			im-config evolution synapt-getic shotwell gnome-todo \
+			transmission-gtk gnome-characters gnome-music \
+			simple-scan vinagre file-roller gnome-documents
+	;;
+
+	dos )
+		apt-get purge gnome-games gnome-sound-recorder im-config \
+			evolution synapt-getic shotwell gnome-todo \
+			transmission-gtk gnome-characters gnome-music \
+			simple-scan vinagre file-roller gnome-documents
+	;;
+
+	ds )
+		apt-get purge gnome-games gnome-sound-recorder im-config \
+			evolution synapt-getic shotwell gnome-todo \
+			transmission-gtk gnome-characters gnome-music \
+			malcontent file-roller gnome-documents
+	;;
+
+	dt | dus )
+		apt-get purge epiphany gnome-games gnome-sound-recorder \
+			im-config evolution synapt-getic shotwell gnome-todo \
+			transmission-gtk gnome-characters gnome-music \
+			malcontent file-roller gnome-documents seahorse
+
+		apt-get install gnome-connections power-profiles-daemon
+	;;
+
+	* )
+		printf '%b\n' "${0##*/}: '$1' is an invalid argument\n" "$help" 1>&2
+		exit 1
+	;;
 
 esac
+
+apt-get autoremove
+apt-get update
+apt-get upgrade
